# Generated by Django 5.0.2 on 2024-05-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_message_timestamp_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
